[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

# Redirect API requests to the functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Allow direct access to Netlify functions - commented out to fix deployment issue
# [[redirects]]
#   from = "/.netlify/functions/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
